file=open("tops1.txt","w")
file.write("this is file management demo using python")
file.close()
print("file write successfully")
print("*******************************************************")

file=open("tops1.txt","r")
print(file.read())
file.close()
print("*******************************************************")

file=open("tops1.txt","a")
file.write("\ntish file is now append")
file.close()
print("file is append successfully")
print("*******************************************************")


file=open("tops1.txt","r")
print(file.read())
file.close()
print("*******************************************************")

file=open("tops2.txt","w+")
file.write("this is w+ mode using python")
print("file current position is :",file.tell())
file.seek(0)
print("file data :",file.read())
file.close()
print("*******************************************************")
